version: "2.0"
volumes:
  postgresql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./postgresql/data
services:
  postgresql:
    image: postgres:14.9-alpine3.18
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: task-manager
      POSTGRES_USER: task-manager
      POSTGRES_DB: task-manager
      PGDATA: /var/lib/postgresql/data/db-files/
    ports:
      - "5432:5432"