version: "2.0"
volumes:
  postgresql-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./postgresql/data
services:
  postgresql:
    image: postgres:14.9-alpine3.18
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: project-management
      POSTGRES_USER: project-management
      POSTGRES_DB: project-management
      PGDATA: /var/lib/postgresql/data/db-files/
    ports:
      - "5432:5432"
  project-management-service:
    image: project-management/project-management-service:0.1
    ports:
      - "5000:5000"
    environment:
      POSTGRES_DSN: postgresql://project-management:project-management@172.18.0.1:5432/project-management